# Materials and Methods

## Data

We used historical deforestation maps for Madagascar at 30m resolution for three time-periods: 1990-2000, 2000-2010, and 2010-2017 [@Vieilledent2018]. We tried to model the observed spatial deforestation process on the period 2000-2010 at the national level. Period 1990-2000 was used to compute the distance to past deforestation for each forest pixel in 2000. Period 2010-2017 was used to compare model forecasts with observations.

To explain the observed spatial deforestation on the period 2000-2010, we considered various spatial explicative variables describing: topography (altitude and slope), accessibility (distances to nearest road, town and river), forest landscape (distance to forest edge), deforestation history (distance to past deforestation) and land-tenure variables (protected area system). Characteristics of each variables are summarized in Tab. \@ref(tab:variables).

Altitude (in m) and slope (in degree) at 90m resolution were obtained from the SRTM Digital Elevation Database v4.1 (<http://srtm.csi.cgiar.org/>). Distances (in m) to nearest road, town and river at 150m resolution were derived from the OpenStreetMap (OSM) project for Madagascar (<http://www.geofabrik.de/>). To obtain the road network in Madagascar, we considered the categories "motorway", "trunk", "primary", "secondary" and "tertiary" for the "highway" key in OSM. To obtain the network of populated places in Madagascar (that we simply call "towns" in the present study), we considered the categories "city", "town" and "village" for the "place" key in OSM. To obtain the river network in Madagascar, we considered the categories "river" and "canal" for the "waterway" key in OSM. For a more detailed description of each category, see the OSM wiki page (<https://wiki.openstreetmap.org/wiki/Tags>). Distance to forest edge was computed at 30m resolution from the forest cover map in 2000. Distance to past deforestation was computed at 30m resolution from the 1990-2000 forest cover change map. For the protected area system, we used the 20/12/2010 version of the SAPM "Système des Aires Protégées à Madagascar" (<http://rebioma.net/>) and considered both Protected Areas (created before 2003) and New Protected Areas in the SAPM terminology. Polygons representing protected areas were rasterized at 30m resolution. In total, we obtained 8 spatial variables that could explained the location of the deforestation.

## Models

We compared two deforestation models. The first model described in Eq. \@ref(eq:glm) is a simple logistic regression model, a special case of generalized linear model (GLM) for binary data. This model is denoted "glm" in subsequent sections and results. We considered the random variable $y_i$ which takes value 1 if the forest pixel $i$ is deforested on the period 2000-2010 and 0 if it is not. We assumed that $y_i$ follows a Bernoulli distribution of parameter $\theta_i$. In our model, $\theta_i$ represents the spatial probability of deforestation for pixel $i$. We assumed that $\theta_i$ is linked, through a logit function, to a linear combination of the explicative variables $X_i \beta$, where $X_i$ is the vector of explicative variables for pixel $i$ and $\beta$ is the vector of model parameters to be estimated.

\begin{equation}
\begin{split}
  y_i \sim \mathcal{B}ernoulli(\theta_i)\\
  \text{logit}(\theta_i) = X_i \beta
\end{split}
(\#eq:glm)
\end{equation}

The second model described in Eq. \@ref(eq:icar) includes additional random effects $\rho_j$ for each spatial cell $j$ of a 10 $\times$ 10 km grid covering Madagascar. We assumed that random effects are spatially autocorrelated through an intrinsic conditional autoregressive (iCAR) model [@Besag1991;@Banerjee2014]. This model is denoted "icar" in subsequent sections and results. In an iCAR model, the random effect $\rho_j$ associated to cell $j$ depends on the values of the random effects $\rho_{j^{\prime}}$ associated to neighbouring cells $j^{\prime}$. In our case, the neighbouring cells are cells connected to the target cell $j$ through a common border or corner (cells defined by the "king move" in chess). The number of neighbouring cells for cell $j$, which might vary, is denoted $n_j$. 

\begin{equation}
\begin{split}
  y_i \sim \mathcal{B}ernoulli(\theta_i)\\
  \text{logit}(\theta_i) = X_i \beta + \rho_j\\
  \rho_j \sim \mathcal{N}ormal(\sum_{j^{\prime}} \rho_{j^{\prime}} / n_j,V_{\rho} / n_j)
\end{split}
(\#eq:icar)
\end{equation}

The first model can be viewed as a "process-based" model for which variables are selected on an _a priori_ knowledge of the deforestation process. For example, we assumed that the risk of deforestation decreases with the distance to road and forest edge, and is lower in protected areas. The second model can be viewed as a model combining a "process-based" part and a "pattern-oriented" part. Additional spatial random effects $\rho_j$ account for unmeasured or unmeasurable variables that explain a part of the residual spatial variation in the deforestation process (the residual spatial "pattern") that is not explained by the fixed environmental variables ($X_i$). While the first model has only 9 parameters to be estimated (one intercept parameter plus 8 slope parameters for the explicative variables), the second model has 6,266 parameters to be estimated, including the 6,257 spatial random effects for the 10 $\times$ 10 km cells covering whole Madagascar (for which lands cover 587 000 km$^2$)

We used a random sample of 20,000 forest pixels in 2000 to fit the two models. The sample was stratified between 10,000 deforested pixels in 2000-2010 and 10,000 non-deforested pixels. A balanced sample between deforested and non-deforested pixels is preferable in our case [@Dezecache2017]. First, deforestation events are rare (~1 %/yr) and a non-stratified sample would lead to very few observations of deforestation events, rendering difficult a good estimation of the slope parameters for the explicative variables. Second, only the value of the linear model intercept is affected by this balanced sampling, which is not the case for the slope or random parameters. In our case, a biased estimate of the intercept is not an issue, as we are not interested in estimating the intensity of deforestation but the relative probability of deforestation between pixels.

Parameter inference was done in a hierarchical Bayesian framework. Non-informative priors were used for all parameters: $\beta \sim Normal(\text{mean}=0,\text{var}=10^6)$ and $V_{\rho} \sim 1/Gamma(\text{shape}=0.05,\text{rate}=0.0005)$. We run a Markov Chain Monte Carlo (MCMC) of 7000 iterations. We discarded the first 2000 iterations (burn-in phase) and we thinned the chain each 5 iterations (to reduce autocorrelation between samples). We obtained 1000 estimates for each parameter. MCMC convergence was visually checked looking at MCMC traces and parameter posterior distributions. Function `model_binomial_iCAR()` from the `forestatrisk` Python package was used for parameter inference. This function calls an adaptive Metropolis-within-Gibbs algorithm [@Rosenthal2011] written in C for maximum computation speed. 

## Model comparison using percentage of deviance explained and cross-validation

We computed the deviance $\mathcal{D}$ of the two models with the formula $\mathcal{D}=-2 \log \mathcal{L}$, $\mathcal{L}$ being the likelihood of the model, i.e. the probability of observing the data given the model and estimated parameters. We compared the deviance of the two models with the deviances of both the "null" model and the "full" model. The "null" model assumes a constant probability of deforestation for all observations and has only one parameter, the intercept of the linear relationship. At the other extreme, the "full" model has as many parameters as there are observations. We then computed the percentage of deviance explained by each model, considering that the "null" model explains 0% of the deviance and the "full" model explains 100% of the deviance.

We also performed a cross-validation to compare models using an independent validation data-set of 20,000 forest pixels in 2000. Again, the sample was stratified between 10,000 deforested pixels in 2000-2010 and 10,000 non-deforested pixels. We used models' predictions for this set of independent observations to compute several accuracy indices: the Area Under the ROC Curve (AUC), the Figure of Merit (FOM), the Overall Accuracy (OA), the Expected Accuracy (EA), the Kappa of Cohen (K), the Specificity (Spe), the Sensitivity(Sen), and the True Skill Statistics (TSS). Detailed description of these indices can be found in @Pontius2008 (for the FOM) and @Liu2011 (for all the other indices). Formulas used to compute the indices are presented in Appendix 1.

Because the value of these indices depends on the deforestation rate [@Pontius2008], we computed the accuracy indices for various ratios of deforested vs. non-deforested pixels: 1, 5, 10, 25 and 50%. To do so, we selected at random a subsample of the deforested pixels in our validation data-set.

## Forecasting deforestation

## Forecasts skill scores

\newpage