---
title: "`r params$title`"
author: "`r params$author`"
date: "`r params$date`"
fontsize: 12pt
output:
  bookdown::gitbook:
    number_sections: yes
    split_by: chapter  
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit: null
      download: ["pdf"]
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing:
        facebook: yes
        twitter: yes
        google: no
        linkedin: no
        weibo: no
        instapper: no
        vk: no
        all: ['facebook', 'google', 'twitter', 'linkedin', 'weibo', 'instapaper']  
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    keep_tex: no
    latex_engine: pdflatex
    number_sections: yes
    toc: no
    includes:
      in_header: header.tex
      before_body: doc_prefix.tex
bibliography: bib/biblio.bib
biblio-style: bib/jae.bst
link-citations: yes
csl: bib/journal-of-applied-ecology.csl
---

```{r options, echo=FALSE, results="hide"}
library(bookdown)
library(knitr)
library(kableExtra)
opts_chunk$set(echo=FALSE, cache=FALSE,
               # results="hide", 
               warning=FALSE,
               message=FALSE, highlight=TRUE,
               # fig.show="hide",
			   size="small",
               fig.align="center",
               fig.pos="H",
               tidy=FALSE)
```

# Abstract {-}

Deforestation models are useful tools in landscape ecology. They can be used to identify the main drivers of deforestation and estimate their relative contribution. When spatially explicit, models can also be used to predict the location of future deforestation. Deforestation forecasts can be used to estimate associated CO$_2$ emissions responsible of climate change, prioritize areas for conservation and identify refuge areas for biodiversity. Most of spatial deforestation models includes landscape variables such as the distance to forest edge, the distance to nearest road or the presence of protected areas. Such variables commonly explain a small part of the deforestation process and a large spatial variability remains unexplained by the model. 

In the present study, we show how using an intrinsic conditional autoregressive (iCAR) model in a hierarchical Bayesian approach can help structure the residual spatial variability in the deforestation process and obtain more realistic predictions of the deforestation. We take Madagascar as a case study considering deforestation on the period 1990-2010 and forecasting deforestation on the period 2010-2050. We demonstrate that accounting for spatial autocorrelation increases the percentage of explained deviance of 21 points for the deforestation model in Madagascar. We also illustrate the use of the newly developed `forestatrisk` Python module to rapidly estimate the numerous parameters of a deforestation model including an iCAR process and efficiently forecast deforestation on large geographical areas at high spatial resolution.

We advocate the use of such models to obtain more accurate land-use change predictions. Such an approach could be used to estimate better the impact of future deforestation in the global carbon cycle and define more efficient strategies for biodiversity conservation in tropical countries.

**Keywords:** deforestation, forecasts, forest cover change, forest refuge areas, Madagascar, random effects, spatial autocorrelation, spatial modelling, variability

Target journals (selection): _Conservation Biology_ (IF: 5.89), _Biological Conservation_ (IF: 4.66), _Environmental Research Letters_ (IF: 4.54), _Landscape Ecology_ (IF: 3.83), _PeerJ_ (IF: 2.2).

\newpage